"""Fetches every tier-1/2 (RSS) source in config/sources.yaml."""
import re
import socket
import threading
import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
import yaml
import requests
import feedparser
import config as C

_TAG_RE = re.compile(r"<[^>]+>")

# Many news sites 403/rate-limit feedparser's default bare "python-feedparser"
# User-Agent as a bot. A normal browser UA avoids that class of silent failure.
_USER_AGENT = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
               "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")

# feedparser has no built-in per-request timeout — without this, one slow/dead
# source can hang the whole collect cycle.
_FETCH_TIMEOUT_SECONDS = 15

# Strips control characters (0x00-0x08, 0x0B, 0x0C, 0x0E-0x1F, 0x7F) that are
# illegal inside XML. Several sources (CCTV, G1/Globo, Ahram Online, Ethiopian
# News Agency, Jakarta Post) mis-declare their encoding and leak stray control
# bytes into the feed body — this is one cause of "not well-formed (invalid
# token)" parse failures, not a broken feed per se.
_INVALID_XML_CHARS_RE = re.compile(u"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")

# A second, very common cause of the exact same "not well-formed (invalid
# token)" error: a raw, un-escaped "&" in the feed body (e.g. "Politics &
# Economy" instead of the XML-correct "Politics &amp; Economy"). Common in
# feeds generated by CMS plugins that don't escape their own output.
# Matches any "&" NOT already starting a valid XML entity, and escapes it.
_BARE_AMPERSAND_RE = re.compile(r"&(?!amp;|lt;|gt;|quot;|apos;|#[0-9]+;|#x[0-9a-fA-F]+;)")


def _clean(text):
    """Some feeds (e.g. Xinhua) embed raw HTML anchor tags inside the
    title/summary fields. Strip tags so the dashboard/email never shows
    literal <a href=...> markup as text."""
    if not text:
        return ""
    return _TAG_RE.sub("", text).strip()


def load_sources():
    with open(C.SOURCES_FILE, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data.get("sources", [])


# Per-source outcome of the most recent fetch_all() call in this process —
# powers the dashboard's "Sources in use" panel (web.py's
# _sources_with_status(), which expects exactly this shape: a dict keyed
# by source name with status/count/message/checked_at). Module-level +
# lock because it's written by the scheduler thread and read by Flask's
# request thread in run_all.py.
_status_lock = threading.Lock()
_source_status = {}


def get_source_status():
    """Snapshot of each source's last fetch_all() outcome. Empty until
    fetch_all() has run at least once in this process."""
    with _status_lock:
        return {name: dict(info) for name, info in _source_status.items()}


def _record_status(name, status, count, message=None):
    with _status_lock:
        _source_status[name] = {
            "status": status,      # "ok" | "warning" | "error" | "disabled"
            "count": count,
            "message": message,
            "checked_at": datetime.datetime.utcnow().isoformat(),
        }


def _fetch_feed(url):
    """Fetch + parse one feed, with two layers of resilience beyond a plain
    feedparser.parse(url):
      1. Uses `requests` to fetch the raw bytes instead of letting feedparser
         open the URL itself — `requests` ships/uses a proper CA bundle
         (certifi), which fixes the class of SSL "certificate verify failed"
         errors that plain urllib hits on some Windows Python installs (seen
         on IRNA).
      2. Strips illegal XML control characters from the raw response before
         handing it to feedparser — fixes the "not well-formed (invalid
         token)" class of errors caused by a source mis-declaring its
         encoding, without needing a different URL.
    Returns a feedparser FeedParserDict either way (same interface as
    feedparser.parse), so callers don't need to change.
    """
    try:
        resp = requests.get(
            url,
            headers={"User-Agent": _USER_AGENT},
            timeout=_FETCH_TIMEOUT_SECONDS,
        )
        resp.raise_for_status()
        cleaned = _INVALID_XML_CHARS_RE.sub("", resp.text)
        cleaned = _BARE_AMPERSAND_RE.sub("&amp;", cleaned)
        return feedparser.parse(cleaned)
    except requests.exceptions.RequestException:
        # Network/HTTP-level failure (DNS, timeout, 403, TLS, etc.) — fall
        # back to feedparser's own fetch in case `requests` and feedparser
        # disagree on some edge case, but don't hide the real error if both fail.
        return feedparser.parse(url, agent=_USER_AGENT)



# Fetching sources one at a time meant a single slow/dead feed (a full
# _FETCH_TIMEOUT_SECONDS read timeout) delayed every source behind it —
# with ~15 sources that could push one collect cycle well past gunicorn's
# worker timeout (see web.py's /trigger-collect), which showed up as
# repeated "WORKER TIMEOUT" / SIGKILL loops in production even though each
# individual fetch was behaving as designed. Fetching is I/O-bound, so a
# small thread pool lets slow sources overlap instead of stacking up —
# total wall-clock time becomes roughly the slowest single source instead
# of the sum of all of them.
_MAX_CONCURRENT_FETCHES = 8


def _process_feed(src, feed):
    """Turns a parsed feed into article dicts and records its status.
    Shared by the (now parallel) fetch path so the status/print behavior
    is identical to before."""
    if feed.bozo and not feed.entries:
        # Malformed/blocked response with zero usable entries — the
        # single biggest silent cause of "no new items ever" for a
        # given source. Surfaced here instead of swallowed.
        msg = str(feed.get("bozo_exception", "malformed feed"))
        print(f"[rss] {src['name']}: 0 entries, feed error: {msg}")
        _record_status(src["name"], "error", 0, msg)
        return []
    elif feed.bozo:
        # Entries came through despite a parse warning — usually
        # harmless (minor XML quirk), but worth a heads-up once.
        print(f"[rss] {src['name']}: {len(feed.entries)} entries (feed had a parse warning, used anyway)")
        _record_status(src["name"], "warning", len(feed.entries), "parse warning, used anyway")
    else:
        print(f"[rss] {src['name']}: {len(feed.entries)} entries")
        _record_status(src["name"], "ok", len(feed.entries))

    out = []
    for entry in feed.entries[:30]:
        out.append({
            "title": _clean(entry.get("title", "")),
            "url": entry.get("link", "").strip(),
            "source": src["name"],
            "country": src.get("country", ""),
            "summary": _clean(entry.get("summary", ""))[:500],
            "published": entry.get("published", entry.get("updated", "")),
        })
    return out


def fetch_all(tiers=(1, 2)):
    """Returns a flat list of article dicts from every RSS source in `tiers`.
    Prints a per-source item count so a dead/blocked feed is visible instead
    of silently contributing 0 items and looking like "no new content".

    Fetches sources concurrently (see _MAX_CONCURRENT_FETCHES) so one slow
    source doesn't hold up every source behind it."""
    articles = []
    to_fetch = []
    for src in load_sources():
        if not src.get("enabled", True):
            # Source flagged off in sources.yaml (dead feed, or
            # confirmed bot-blocked beyond what headers/cleanup fix) —
            # skip without noise instead of retrying every cycle.
            _record_status(src["name"], "disabled", 0, "disabled in sources.yaml")
            continue
        if src.get("type") != "rss" or src.get("tier") not in tiers:
            continue
        to_fetch.append(src)

    if not to_fetch:
        return articles

    old_timeout = socket.getdefaulttimeout()
    socket.setdefaulttimeout(_FETCH_TIMEOUT_SECONDS)
    try:
        with ThreadPoolExecutor(max_workers=min(_MAX_CONCURRENT_FETCHES, len(to_fetch))) as pool:
            # Keyed by list index rather than source name — two sources
            # sharing a name (a copy-paste in sources.yaml, say) would
            # otherwise silently collide and one feed's results would
            # clobber the other's in `results`.
            future_to_idx = {pool.submit(_fetch_feed, src["url"]): i for i, src in enumerate(to_fetch)}
            results = {}
            for future in as_completed(future_to_idx):
                idx = future_to_idx[future]
                src = to_fetch[idx]
                try:
                    results[idx] = future.result()
                except Exception as e:
                    print(f"[rss] {src['name']}: FAILED ({e})")
                    _record_status(src["name"], "error", 0, str(e))
                    results[idx] = None

            for idx, src in enumerate(to_fetch):
                feed = results.get(idx)
                if feed is None:
                    continue
                articles.extend(_process_feed(src, feed))
    finally:
        socket.setdefaulttimeout(old_timeout)
    return articles
